### ISSUE TITLE
Doesn't allow empty action-types.yml if action has no inputs and outputs

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-typing#22]
```
Exception in thread "main" com.charleskorn.kaml.EmptyYamlDocumentException at <root> on line 1, column 1: The YAML document is empty.
	at com.charleskorn.kaml.YamlParser.<init>(YamlParser.kt:41)
	at com.charleskorn.kaml.Yaml.parseToYamlNodeFromReader(Yaml.kt:63)
	at com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:52)
	at com.charleskorn.kaml.Yaml.decodeFromString(Yaml.kt:44)
	at it.krzeminski.githubactionstyping.parsing.TypesManifestParsingKt.parseTypesManifest(TypesManifestParsing.kt:35)
	at it.krzeminski.githubactionstyping.ManifestsToReportKt.manifestsToReport(ManifestsToReport.kt:11)
	at it.krzeminski.githubactionstyping.MainKt.main(Main.kt:19)
	at it.krzeminski.githubactionstyping.MainKt.main(Main.kt)
```

When writing

```
inputs:
```

this is returned:
```
Exception in thread "main" com.charleskorn.kaml.InvalidPropertyValueException at inputs on line 1, column 8: Value for 'inputs' is invalid: Unexpected null or empty value for non-null field.
	at com.charleskorn.kaml.YamlMapLikeInputBase.fromCurrentValue(YamlMapLikeInputBase.kt:55)
	at com.charleskorn.kaml.YamlObjectInput.beginStructure(YamlObjectInput.kt:78)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:103)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at it.krzeminski.githubactionstyping.parsing.TypesManifest$$serializer.deserialize(TypesManifestParsing.kt:8)
	at it.krzeminski.githubactionstyping.parsing.TypesManifest$$serializer.deserialize(TypesManifestParsing.kt:8)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:103)
	at com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:55)
	at com.charleskorn.kaml.Yaml.decodeFromString(Yaml.kt:44)
	at it.krzeminski.githubactionstyping.parsing.TypesManifestParsingKt.parseTypesManifest(TypesManifestParsing.kt:35)
	at it.krzeminski.githubactionstyping.ManifestsToReportKt.manifestsToReport(ManifestsToReport.kt:11)
	at it.krzeminski.githubactionstyping.MainKt.main(Main.kt:19)
	at it.krzeminski.githubactionstyping.MainKt.main(Main.kt)
Caused by: com.charleskorn.kaml.UnexpectedNullValueException at inputs on line 1, column 8: Unexpected null or empty value for non-null field.
	at com.charleskorn.kaml.YamlNullInput.beginStructure(YamlNullInput.kt:32)
	at com.charleskorn.kaml.YamlObjectInput$beginStructure$1.invoke(YamlObjectInput.kt:78)
	at com.charleskorn.kaml.YamlObjectInput$beginStructure$1.invoke(YamlObjectInput.kt:78)
	at com.charleskorn.kaml.YamlMapLikeInputBase.fromCurrentValue(YamlMapLikeInputBase.kt:52)
	... 19 more
```

**Comment by krzema12** [comment]
See https://yaml.org/spec/1.2-old/spec.html#id2805071 - such YAML:

```yaml
inputs:
```

is equivalent to
```yaml
inputs: null
```

Let's try not supporting empty `inputs:`.
